### ISSUE TITLE
Binary hosting

### ISSUE THREAD

**Issue by kimwalisch** [curtisseizert/CUDASieve#2]
Hi Curtis,

It took me quite some time to figure out that you have committed your binary and static library to your GitHub repo!? You are in fact the first guy I am aware of who has done this...

Personally I suggest that you create a dedicated Binary section in your README.md (with some description) where you offer a download link to a binary hosting website such as https://bintray.com (which is free for open source projects). I have done it the same way for my primecount project (https://github.com/kimwalisch/primecount#binaries).

This way your users will not waste 10 minutes to find out how to download your binary!

Greetings,
Kim

**Comment by curtisseizert** [comment]
Done!  Thanks for the heads-up.
