### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by twobombs** [curtisseizert/CUDASieve#8]
After a succesfull compile I found the following not working 

![Screenshot from 2022-05-25 22-14-58](https://user-images.githubusercontent.com/12692227/170359454-9e2e5624-b1ef-4419-8402-395e32fda761.png)

Example with exponents do not seem to work whilst invoking sh inside the binary [?]

i would like to set bottom and top areas for the sieve to measure output, performance in multi GPU/node environments

Any idea towards solving this example would be greatly appreciated :)

**Comment by curtisseizert** [comment]
The CLI pipes the expression to cmd to execute, reads the output, and converts this to a uint64_t. Make sure you can evaluate those expressions in the command line. The function that handles this is host::echo starting on line 121 of main.cpp.

**Comment by curtisseizert** [comment]
Another thought on this: if you are trying to have this run fast with multiple calls, I would use the API. The CLI adds a lot of overhead that is fine for demonstrating proof of principle or benchmarking, but it is much faster if you are going to run numerous calls to just use the API functions that are listed in the readme.

**Comment by twobombs** [comment]
tnx - will look into this :)
